import { Inter } from "next/font/google";
import "./styles/global.css";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Signout from "./signout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {!!session && <Signout />}
          {!session && <Link href="/">Login</Link>}
        </nav>
        {children}
      </body>
    </html>
  );
}
